version: "3.9"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/tmp
    ports:
      - "48200:5432"
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ./sos-centar-api
      dockerfile: Dockerfile
    ports:
      - "48201:5000"
    depends_on:
      - database
    env_file:
      - .env
  web:
    image: ${DOCKER_REGISTRY-}sos-web
    build:
      context: ./sos-web
      dockerfile: Dockerfile
    ports:
      - "48202:3000"
  

