version: "3"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/tmp
    ports:
      - "48200:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
        timeout: 45s
        interval: 10s
        retries: 10
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ./sos-centar-api
      dockerfile: Dockerfile
    ports:
      - "48201:5000"
    depends_on:
      database
        condition: service_healthy
    env_file:
      - .env
  web:
    image: ${DOCKER_REGISTRY-}sos-web
    build:
      context: ./sos-web
      dockerfile: Dockerfile
    ports:
      - "48202:3000"
  pgadmin:
    image: dpage/pgadmin4
    container_name: sos-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "48203:80"
    depends_on:
      database
        condition: service_healthy
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
  postgres-data:
