version: "3.9"

services:
  database:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ./sos-centar-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  

