# Generated by Django 3.2.7 on 2021-09-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_column='Id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FirstName', max_length=160)),
                ('last_name', models.CharField(db_column='LastName', max_length=160)),
                ('email', models.CharField(db_column='Email', max_length=160)),
                ('password', models.CharField(db_column='Password', max_length=160)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
